EXCHANGES: dict[str, dict[str, str]] = {
    "AMS": {"name": "Euronext Amsterdam", "location": "Netherlands"},
    "AQS": {"name": "Aquis Exchange", "location": "UK / Europe"},
    "ASE": {"name": "American Stock Exchange (NYSE American)", "location": "United States"},
    "ASX": {"name": "Australian Securities Exchange", "location": "Australia"},
    "ATH": {"name": "Athens Stock Exchange (ATHEX)", "location": "Greece"},
    "BER": {"name": "Berlin Stock Exchange", "location": "Germany"},
    "BRU": {"name": "Euronext Brussels", "location": "Belgium"},
    "BTS": {"name": "Bratislava Stock Exchange", "location": "Slovakia"},
    "BUD": {"name": "Budapest Stock Exchange", "location": "Hungary"},
    "CPH": {"name": "Nasdaq Copenhagen", "location": "Denmark"},
    "DOH": {"name": "Qatar Stock Exchange", "location": "Qatar"},
    "DUS": {"name": "Düsseldorf Stock Exchange", "location": "Germany"},
    "EBS": {"name": "SIX Swiss Exchange", "location": "Switzerland"},
    "FRA": {"name": "Frankfurt Stock Exchange", "location": "Germany"},
    "GER": {"name": "XETRA (Frankfurt Electronic)", "location": "Germany"},
    "HAM": {"name": "Hamburg Stock Exchange", "location": "Germany"},
    "HAN": {"name": "Hanover Stock Exchange", "location": "Germany"},
    "HEL": {"name": "Nasdaq Helsinki", "location": "Finland"},
    "ICE": {"name": "Nasdaq Iceland", "location": "Iceland"},
    "IST": {"name": "Borsa Istanbul", "location": "Turkey"},
    "JPX": {"name": "Japan Exchange Group (Tokyo Stock Exchange)", "location": "Japan"},
    "KSC": {"name": "Korea Stock Exchange (KRX)", "location": "South Korea"},
    "LIS": {"name": "Euronext Lisbon", "location": "Portugal"},
    "LIT": {"name": "Nasdaq Vilnius (Vilnius Stock Exchange)", "location": "Lithuania"},
    "LSE": {"name": "London Stock Exchange", "location": "United Kingdom"},
    "MCE": {"name": "Bolsa de Madrid (Madrid Stock Exchange)", "location": "Spain"},
    "MCX": {"name": "Moscow Exchange", "location": "Russia"},
    "MEX": {"name": "Bolsa Mexicana de Valores (Mexican Stock Exchange)", "location": "Mexico"},
    "MIL": {"name": "Borsa Italiana (Milan)", "location": "Italy"},
    "MUN": {"name": "Munich Stock Exchange (Gettex)", "location": "Germany"},
    "NCM": {"name": "Nasdaq Capital Market", "location": "United States"},
    "NEO": {"name": "NEO Exchange", "location": "Canada"},
    "NGM": {"name": "Nordic Growth Market", "location": "Sweden"},
    "NIM": {"name": "Nasdaq International Market", "location": "United States"},
    "NMS": {"name": "Nasdaq Global Select Market", "location": "United States"},
    "NYQ": {"name": "New York Stock Exchange (NYSE)", "location": "United States"},
    "OSL": {"name": "Oslo Børs", "location": "Norway"},
    "PAR": {"name": "Euronext Paris", "location": "France"},
    "PCX": {"name": "NYSE Arca", "location": "United States"},
    "PNK": {"name": "OTC Markets (Pink Sheets)", "location": "United States"},
    "PRA": {"name": "Prague Stock Exchange", "location": "Czech Republic"},
    "SAU": {"name": "Saudi Exchange (Tadawul)", "location": "Saudi Arabia"},
    "SES": {"name": "Singapore Exchange (SGX)", "location": "Singapore"},
    "SET": {"name": "Stock Exchange of Thailand", "location": "Thailand"},
    "STO": {"name": "Nasdaq Stockholm", "location": "Sweden"},
    "TAI": {"name": "Taiwan Stock Exchange (TWSE)", "location": "Taiwan"},
    "TLV": {"name": "Tel Aviv Stock Exchange (TASE)", "location": "Israel"},
    "TOR": {"name": "Toronto Stock Exchange (TSX)", "location": "Canada"},
    "TWO": {"name": "Taipei Exchange (TPEx)", "location": "Taiwan"},
    "VIE": {"name": "Vienna Stock Exchange (Wiener Börse)", "location": "Austria"},
}

CURRENCIES: dict[str, dict[str, str]] = {
    "AUD": {"name": "Australian Dollar", "country": "Australia"},
    "CAD": {"name": "Canadian Dollar", "country": "Canada"},
    "CHF": {"name": "Swiss Franc", "country": "Switzerland"},
    "CNY": {"name": "Chinese Yuan Renminbi", "country": "China"},
    "CZK": {"name": "Czech Koruna", "country": "Czech Republic"},
    "DKK": {"name": "Danish Krone", "country": "Denmark"},
    "EUR": {"name": "Euro", "country": "Eurozone"},
    "GBP": {"name": "British Pound Sterling", "country": "United Kingdom"},
    "HUF": {"name": "Hungarian Forint", "country": "Hungary"},
    "ILA": {"name": "Israeli Agora (1/100 ILS)", "country": "Israel"},
    "ISK": {"name": "Icelandic Króna", "country": "Iceland"},
    "JPY": {"name": "Japanese Yen", "country": "Japan"},
    "KRW": {"name": "South Korean Won", "country": "South Korea"},
    "MXN": {"name": "Mexican Peso", "country": "Mexico"},
    "NOK": {"name": "Norwegian Krone", "country": "Norway"},
    "QAR": {"name": "Qatari Riyal", "country": "Qatar"},
    "RUB": {"name": "Russian Ruble", "country": "Russia"},
    "SAR": {"name": "Saudi Riyal", "country": "Saudi Arabia"},
    "SEK": {"name": "Swedish Krona", "country": "Sweden"},
    "SGD": {"name": "Singapore Dollar", "country": "Singapore"},
    "THB": {"name": "Thai Baht", "country": "Thailand"},
    "TRY": {"name": "Turkish Lira", "country": "Turkey"},
    "TWD": {"name": "New Taiwan Dollar", "country": "Taiwan"},
    "USD": {"name": "United States Dollar", "country": "United States"},
}
